spring:
  cloud:
    gateway:
      routes:
        - id: path_admin
          uri: lb://mall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /mall-admin/$\{segment}