spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_pms?serverTimezone=Asia/Shanghai
    username: root
    password: a123
  cloud:
    #sentinel
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      datasource:
        ds1:
          nacos:
            data-id: mz-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow


#    type: com.alibaba.druid.pool.DruidDataSource druid的配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  type-aliases-package: com.rl.entity